//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accident()
        {
            this.Material_Damage = new HashSet<Material_Damage>();
            this.Driver = new HashSet<Driver>();
            this.Passenger = new HashSet<Passenger>();
            this.Police_Officer = new HashSet<Police_Officer>();
            this.Vehicle = new HashSet<Vehicle>();
            this.Date_and_Time = DateTime.Today;
        }
    
        public int Accident_id { get; set; }
        public System.DateTime Date_and_Time { get; set; }
        public string Location { get; set; }
        public string Accident_Type { get; set; }
        public string Description { get; set; }
        public int id_weather_conditions { get; set; }
    
        public virtual Weather_Conditions Weather_Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Damage> Material_Damage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Police_Officer> Police_Officer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}
