//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTP
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class DTPEntities : DbContext
    {
        private static DTPEntities _context;
        public DTPEntities()
            : base("name=DTPEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static DTPEntities GetContext()
        {
            if (_context == null)
                _context = new DTPEntities();
            return _context;
        }
        public static List<Driver> GetAllDriver()
        {
            return GetContext().Driver.ToList();
        }
        public static List<Accident> GetAllAccidentS()
        {
            return GetContext().Accident.ToList();
        }

        public static List<Material_Damage> GetAllDamage()
        {
            return GetContext().Material_Damage.ToList();
        }

        public static List<Passenger> GetAllPassengers()
        {
            return GetContext().Passenger.ToList();
        }

        public static List<Police_Officer> GetAllPolice()
        {
            return GetContext().Police_Officer.ToList();
        }

        public static List<Vehicle> GetAllVehicle()
        {
            return GetContext().Vehicle.ToList();
        }

        public static List<Weather_Conditions> GetAllWeather()
        {
            return GetContext().Weather_Conditions.ToList();
        }
        public virtual DbSet<Accident> Accident { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Material_Damage> Material_Damage { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Police_Officer> Police_Officer { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<Weather_Conditions> Weather_Conditions { get; set; }
    }
}
