//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Damage
    {
        public int Damage_ID { get; set; }
        public string Damage_Description { get; set; }
        public decimal Estimated_Cost { get; set; }
        public int id_Accident { get; set; }
    
        public virtual Accident Accident { get; set; }
    }
}
